<?php
    /** @var \BroCode\AmqpMonitor\Block\Adminhtml\AmqpConfiguration $block */
    $amqpConfiguration = $block->getAmqpConfiguration();
    $managementApiConfiguration = $block->getManagementApiConfiguration();
    if (!empty($amqpConfiguration) || !empty($managementApiConfiguration)):
?>
<h2><?= __('AMQP Configuration') ?></h2>
    <div style="display: grid; grid-template-columns: repeat(2, 1fr);">
<?php endif; ?>
<?php if (!empty($amqpConfiguration)): ?>
    <div style="padding: 0 10px 10px 0;">
        <table class="admin__table-primary dashboard-data">
            <thead>
            <tr><th class="data-grid-th no-link" colspan="2"><?= __('Message Queue Configuration') ?></th></tr>
            <tr>
                <th class="data-grid-th no-link"><?= _('Key') ?></th>
                <th class="data-grid-th no-link"><?= __('Value') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($amqpConfiguration as $key => $value): ?>
                <tr>
                    <td><?= $key ?></td>
                    <td><?= $value ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
<?php if (!empty($managementApiConfiguration)): ?>
    <div style="padding: 0 10px 10px 0;">
        <table class="admin__table-primary dashboard-data">
            <thead>
            <tr><th class="data-grid-th no-link" colspan="2"><?= __('Management Api Configuration') ?></th></tr>
            <tr>
                <th class="data-grid-th no-link"><?= _('Key') ?></th>
                <th class="data-grid-th no-link"><?= __('Value') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($managementApiConfiguration as $key => $value): ?>
                <tr>
                    <td><?= $key ?></td>
                    <td><?= $value ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
<?php if (!empty($amqpConfiguration) || !empty($managementApiConfiguration)): ?>
    </div>
<?php endif; ?>